/* The Habbo Origins hotel views, as the title screen needs them.

   GENERATED by tools/hotel-view-extract.js from the client's own
   hh_entry_*.cct — do not hand-edit, re-run the tool.

   Each hotel is three pictures and a list of clouds:
   assets/img/hotel/<key>-back.png is the sky, <key>-front.png is everything
   built on the ground, and <key>-glow.png is the client's own additive lamp,
   which js/room-lobby.js draws last with globalCompositeOperation "lighter".

   The clouds belong BETWEEN back and front, which is the order the client's
   own element list puts them in, and `x` and `y` are where that hotel starts
   each one. The game does not draw them — see the note in js/room-lobby.js —
   but their positions and their sprites (assets/img/hotel/cloud_*.png, shared:
   every cast ships the same eight) are here for anything that wants them. */
(function () {
    "use strict";
    window.HotelViews = {
    "w": 720,
    "h": 498,
    "dir": "assets/img/hotel/",
    "views": [
        {
            "key": "es",
            "clouds": [
                {
                    "sprite": "cloud_0_right",
                    "x": 443,
                    "y": 96
                },
                {
                    "sprite": "cloud_2_left",
                    "x": 16,
                    "y": 165
                },
                {
                    "sprite": "cloud_3_right",
                    "x": 595,
                    "y": 122
                },
                {
                    "sprite": "cloud_1_left",
                    "x": 205,
                    "y": 105
                },
                {
                    "sprite": "cloud_0_left",
                    "x": 66,
                    "y": 95
                },
                {
                    "sprite": "cloud_1_right",
                    "x": 645,
                    "y": 163
                }
            ]
        },
        {
            "key": "br",
            "clouds": [
                {
                    "sprite": "cloud_1_left",
                    "x": 13,
                    "y": 161
                },
                {
                    "sprite": "cloud_1_right",
                    "x": 588,
                    "y": 115
                },
                {
                    "sprite": "cloud_1_left",
                    "x": 179,
                    "y": 120
                },
                {
                    "sprite": "cloud_0_right",
                    "x": 626,
                    "y": 192
                },
                {
                    "sprite": "cloud_2_right",
                    "x": 698,
                    "y": 75
                },
                {
                    "sprite": "cloud_0_right",
                    "x": 350,
                    "y": 102
                }
            ]
        },
        {
            "key": "uk",
            "clouds": [
                {
                    "sprite": "cloud_0_right",
                    "x": 420,
                    "y": 97
                },
                {
                    "sprite": "cloud_1_left",
                    "x": -10,
                    "y": 161
                },
                {
                    "sprite": "cloud_3_right",
                    "x": 572,
                    "y": 123
                },
                {
                    "sprite": "cloud_1_left",
                    "x": 182,
                    "y": 106
                },
                {
                    "sprite": "cloud_0_left",
                    "x": 43,
                    "y": 96
                },
                {
                    "sprite": "cloud_2_right",
                    "x": 625,
                    "y": 168
                }
            ]
        }
    ]
};
})();
