/* Public rooms, painted rather than built.

   GENERATED by tools/public-room-extract.js — do not edit by hand. Its header
   explains how a public room differs from a private one and where each number
   here comes from.

   A public room is ONE PICTURE plus a walkable mask. There is no floor to lay
   and no walls to raise: `image` is the room, `originX`/`originY` say where
   tile (0,0) sits inside it, and `tileW`/`tileH` are 32x16 rather than the
   64x32 a private room uses — the client drew the big rooms at half scale
   because they do not fit the stage otherwise.

   `mask` is the same shape as a private layout's: one string per row, "0"
   where the floor can be walked and "x" where it cannot. It was derived from
   the artwork rather than read out of the client, which has no such grid —
   Habbo's server sent it at runtime.

   `overlays` is everything drawn ON TOP, in client depth order, kept for a
   later pass: the masks are what put an avatar behind a bookcase. */
(function () {
    "use strict";

    const ROOMS = [
        {
            id: "library", name: "Library", painted: true,
            image: "assets/rooms/library/background.png", imageW: 717, imageH: 486,
            tileW: 32, tileH: 16,
            originX: 290, originY: -20,
            cols: 26, rows: 26, tiles: 98, door: 0,
            mask: [
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxx0xxxxxxxxxxx",
                "xxxxxxxxxxxxxx0000xxxxxxxx",
                "xxxxxxxxxxxxxx00000x0xxxxx",
                "xxxxxxxxxxxxxx0000x000xxxx",
                "xxxxxxxxxxxxxx000x00000xxx",
                "xxxxxxxxxxxxx00xx0000xxxxx",
                "xxxxxxxxxxxxx00000000xxxxx",
                "xxxxxxxxxxxx00000xx000xxxx",
                "xxxxxxxxxx00000000x0000xxx",
                "xxxxxxxxxxxx000000xx0xxxxx",
                "xxxxxxxxxxxxx00000xx0xxxxx",
                "xxxxxxxxxxxxxx00xxxx00xxxx",
                "xxxxxxxxxxxxxx0xxxx0000xxx",
                "xxxxxxxxxxxxxxxx0000xx00xx",
                "xxxxxxxxxxxxxxxxx000xxx00x",
                "xxxxxxxxxxxxxxxxxx00xxxx00",
                "xxxxxxxxxxxxxxxxxxx0xxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            ],
            derived: [
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxx0xxxxxxxxxxx",
                "xxxxxxxxxxxxxx0000xxxxxxxx",
                "xxxxxxxxxxxxxx00000x0xxxxx",
                "xxxxxxxxxxxxxx0000x000xxxx",
                "xxxxxxxxxxxxxx000x00000xxx",
                "xxxxxxxxxxxxx00xx0000xxxxx",
                "xxxxxxxxxxxxx00000000xxxxx",
                "xxxxxxxxxxxx00000xx000xxxx",
                "xxxxxxxxxx00000000x0000xxx",
                "xxxxxxxxxxxx000000xx0xxxxx",
                "xxxxxxxxxxxxx00000xx0xxxxx",
                "xxxxxxxxxxxxxx00xxxx00xxxx",
                "xxxxxxxxxxxxxx0xxxx0000xxx",
                "xxxxxxxxxxxxxxxx0000xx00xx",
                "xxxxxxxxxxxxxxxxx000xxx00x",
                "xxxxxxxxxxxxxxxxxx00xxxx00",
                "xxxxxxxxxxxxxxxxxxx0xxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            ],
            overlays: [
                { member: "block_light", x: 272, y: 121, w: 42, h: 43, ink: 8, blend: 100, z: 0 },
                { member: "libtable_sd", x: 279, y: 443, w: 64, h: 33, ink: 36, blend: 30, z: 0 },
                { member: "statue_mask2", x: 510, y: 83, w: 49, h: 92, ink: 8, blend: 100, z: 23000 },
                { member: "counter7", x: 264, y: 155, w: 27, h: 23, ink: 36, blend: 100, z: 24000 },
                { member: "comp", x: 268, y: 149, w: 21, h: 28, ink: 36, blend: 100, z: 24010 },
                { member: "counter6", x: 279, y: 162, w: 18, h: 32, ink: 36, blend: 100, z: 25000 },
                { member: "statue_mask1", x: 514, y: 102, w: 143, h: 94, ink: 8, blend: 100, z: 26000 },
                { member: "counter5", x: 263, y: 174, w: 29, h: 28, ink: 36, blend: 100, z: 26000 },
                { member: "pillar", x: 175, y: 135, w: 37, h: 75, ink: 36, blend: 100, z: 27000 },
                { member: "counter4", x: 247, y: 182, w: 29, h: 28, ink: 36, blend: 100, z: 27000 },
                { member: "counter3", x: 235, y: 190, w: 25, h: 28, ink: 36, blend: 100, z: 28000 },
                { member: "counter1", x: 198, y: 188, w: 27, h: 27, ink: 36, blend: 100, z: 28000 },
                { member: "counter2", x: 212, y: 195, w: 32, h: 27, ink: 36, blend: 100, z: 29000 },
                { member: "books", x: 203, y: 183, w: 25, h: 20, ink: 36, blend: 100, z: 29010 },
                { member: "stairs_mask", x: 123, y: 167, w: 18, h: 70, ink: 36, blend: 100, z: 31101 },
                { member: "shelfmask13", x: 560, y: 182, w: 32, h: 74, ink: 36, blend: 100, z: 33101 },
                { member: "left_mask", x: 33, y: 60, w: 94, h: 180, ink: 36, blend: 100, z: 34000 },
                { member: "shelfmask14", x: 576, y: 190, w: 32, h: 74, ink: 36, blend: 100, z: 34000 },
                { member: "shelfmask15", x: 592, y: 198, w: 32, h: 74, ink: 36, blend: 100, z: 35000 },
                { member: "shelfmask16", x: 608, y: 206, w: 32, h: 74, ink: 36, blend: 100, z: 36000 },
                { member: "shelfmask17", x: 624, y: 214, w: 32, h: 74, ink: 36, blend: 100, z: 37000 },
                { member: "shelfmask33", x: 154, y: 218, w: 32, h: 74, ink: 36, blend: 100, z: 37101 },
                { member: "shelfmask7", x: 496, y: 214, w: 32, h: 74, ink: 36, blend: 100, z: 37101 },
                { member: "shelfmask8", x: 512, y: 222, w: 32, h: 74, ink: 36, blend: 100, z: 38000 },
                { member: "shelfmask32", x: 138, y: 226, w: 32, h: 74, ink: 36, blend: 100, z: 38001 },
                { member: "shelfmask27", x: 258, y: 222, w: 32, h: 74, ink: 36, blend: 100, z: 38101 },
                { member: "shelfmask18", x: 640, y: 222, w: 34, h: 75, ink: 36, blend: 100, z: 38101 },
                { member: "shelfmask26", x: 242, y: 230, w: 32, h: 74, ink: 36, blend: 100, z: 39000 },
                { member: "shelfmask9", x: 528, y: 230, w: 32, h: 74, ink: 36, blend: 100, z: 39000 },
                { member: "shelfmask31", x: 122, y: 234, w: 32, h: 74, ink: 36, blend: 100, z: 39001 },
                { member: "shelfmask25", x: 226, y: 238, w: 32, h: 74, ink: 36, blend: 100, z: 40000 },
                { member: "shelfmask10", x: 544, y: 238, w: 32, h: 74, ink: 36, blend: 100, z: 40000 },
                { member: "shelfmask30", x: 106, y: 242, w: 32, h: 74, ink: 36, blend: 100, z: 40001 },
                { member: "shelfmask24", x: 210, y: 246, w: 32, h: 74, ink: 36, blend: 100, z: 41000 },
                { member: "shelfmask11", x: 560, y: 246, w: 32, h: 74, ink: 36, blend: 100, z: 41000 },
                { member: "shelfmask29", x: 90, y: 250, w: 32, h: 74, ink: 36, blend: 100, z: 41001 },
                { member: "shelfmask1", x: 432, y: 246, w: 32, h: 74, ink: 36, blend: 100, z: 41101 },
                { member: "shelfmask23", x: 194, y: 254, w: 32, h: 74, ink: 36, blend: 100, z: 42000 },
                { member: "shelfmask2", x: 448, y: 254, w: 32, h: 74, ink: 36, blend: 100, z: 42000 },
                { member: "shelfmask28", x: 72, y: 258, w: 34, h: 75, ink: 36, blend: 100, z: 42101 },
                { member: "shelfmask12", x: 576, y: 254, w: 34, h: 75, ink: 36, blend: 100, z: 42101 },
                { member: "shelfmask22", x: 178, y: 262, w: 32, h: 74, ink: 36, blend: 100, z: 43000 },
                { member: "shelfmask3", x: 464, y: 262, w: 32, h: 74, ink: 36, blend: 100, z: 43000 },
                { member: "shelfmask21", x: 162, y: 270, w: 32, h: 74, ink: 36, blend: 100, z: 44000 },
                { member: "shelfmask4", x: 480, y: 270, w: 32, h: 74, ink: 36, blend: 100, z: 44000 },
                { member: "shelfmask20", x: 146, y: 278, w: 32, h: 74, ink: 36, blend: 100, z: 45000 },
                { member: "shelfmask5", x: 496, y: 278, w: 32, h: 74, ink: 36, blend: 100, z: 45000 },
                { member: "shelfmask19", x: 128, y: 286, w: 34, h: 75, ink: 36, blend: 100, z: 46101 },
                { member: "shelfmask6", x: 512, y: 286, w: 34, h: 75, ink: 36, blend: 100, z: 46101 },
                { member: "shelf2", x: 55, y: 303, w: 68, h: 58, ink: 8, blend: 100, z: 50000 },
                { member: "stairmask", x: 155, y: 388, w: 19, h: 9, ink: 8, blend: 100, z: 53101 },
                { member: "lamp_a_0_0_0", x: 352, y: 416, w: 13, h: 41, ink: 8, blend: 100, z: 56000 },
                { member: "libtable_a_0_0_0", x: 278, y: 431, w: 66, h: 44, ink: 36, blend: 100, z: 57001 },
                { member: "libtable_b_0_0_0", x: 288, y: 436, w: 46, h: 24, ink: 8, blend: 34, z: 57002 },
                { member: "magazines", x: 308, y: 438, w: 14, h: 14, ink: 8, blend: 100, z: 57003 },
                { member: "lamp_a_0_0_0", x: 106, y: 410, w: 13, h: 41, ink: 8, blend: 100, z: 77000 },
                { member: "lamp_b_0_0_0", x: 327, y: 395, w: 64, h: 56, ink: 33, blend: 100, z: 88000 },
                { member: "lamp_b_0_0_0", x: 81, y: 389, w: 64, h: 56, ink: 33, blend: 100, z: 88000 },
                { member: "top_mask", x: 126, y: 0, w: 235, h: 175, ink: 36, blend: 100, z: 880000 },
                { member: "chandelier", x: 331, y: -21, w: 108, h: 136, ink: 36, blend: 100, z: 880001 },
                { member: "shelf1_mask", x: 204, y: 270, w: 182, h: 148, ink: 36, blend: 100, z: 880001 },
                { member: "block_dark", x: 615, y: 277, w: 42, h: 43, ink: 36, blend: 100, z: 880001 },
                { member: "block_dark", x: 551, y: 309, w: 42, h: 43, ink: 36, blend: 100, z: 880001 },
                { member: "chandelier_light", x: 321, y: 29, w: 130, h: 102, ink: 33, blend: 100, z: 880010 },
            ]
        },
    ];

    /* HAND CORRECTIONS WIN, and survive this file being regenerated.

       The walkable grid above was DERIVED from the artwork by sampling pixel
       colours, which is a good guess and only a guess: it cannot tell a patch
       of floor under a dark arch from the arch, and it has no idea whether the
       builder wants the carpet walked on. js/room-masks.js is hand-written —
       painted in the level editor's Walkable mode — and replaces the derived
       mask outright where it has one.

       Applied here rather than merged into the data above, because this file
       is regenerated from the client whenever the extractor is re-run and
       anything written into it is lost. */
    if (window.RoomMasks) {
        for (const r of ROOMS) {
            const over = window.RoomMasks[r.id];
            if (!Array.isArray(over) || !over.length) continue;
            if (over.length !== r.rows || over.some(row => row.length !== r.cols)) {
                console.warn("RoomMasks: \"" + r.id + "\" is " +
                    over[0].length + "x" + over.length + ", room is " +
                    r.cols + "x" + r.rows + " — override ignored.");
                continue;
            }
            r.mask = over.slice();
            r.tiles = over.join("").split("").filter(c => c !== "x").length;
        }
    }

    const byId = new Map(ROOMS.map(r => [r.id, r]));
    window.RoomPublic = { ROOMS, get: (id) => byId.get(id) || null };

    /* A PUBLIC ROOM IS A LAYOUT LIKE ANY OTHER as far as the rest of the game
       is concerned: it has a size, a mask and a door, which is everything a
       level needs to be normalised, walked and played against. So it joins the
       same list the private rooms are in, and the editor's picker, the level
       record and RoomIso.setLayout all take it without knowing the difference.

       Appended here rather than written into room-layouts.js because both
       files are generated from different casts by different tools, and neither
       should have to know when the other is re-run. Load order does the rest —
       this file comes after room-layouts.js. */
    if (window.RoomLayouts && Array.isArray(window.RoomLayouts.MODELS)) {
        for (const r of ROOMS) {
            if (!window.RoomLayouts.MODELS.some(m => m.id === r.id)) {
                window.RoomLayouts.MODELS.push(r);
            }
        }
        if (typeof window.RoomLayouts.register === "function") {
            ROOMS.forEach(window.RoomLayouts.register);
        }
    }
})();
