/* The room layouts, straight out of the Origins client.

   GENERATED by tools/room-layouts-extract.js from hh_room_private.cct — do
   not edit by hand. The tool's header explains where these come from and why
   only seven of the client's nineteen models are here.

   A layout is a grid and a MASK. `mask` is one string per row, "0" where
   there is floor and "x" where there is not, so a room can have a corner
   taken out of it — which two of these do. Everything that asks "is this a
   tile" has to consult the mask and not just the bounds, because a hole is
   as solid as the wall as far as walking is concerned.

   `door` is the row on the left wall the doorway stands against, taken from
   the model's own leftdoor_open element. */
(function () {
    "use strict";

    const MODELS = [
        {
            id: "a", name: "Classic",
            cols: 8, rows: 13, tiles: 104, door: 4,
            mask: [
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
                "00000000",
            ]
        },
        {
            id: "e", name: "Wide",
            cols: 10, rows: 8, tiles: 80, door: 2,
            mask: [
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
            ]
        },
        {
            id: "d", name: "Long",
            cols: 6, rows: 14, tiles: 84, door: 6,
            mask: [
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
            ]
        },
        {
            id: "c", name: "Square",
            cols: 6, rows: 6, tiles: 36, door: 2,
            mask: [
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
                "000000",
            ]
        },
        {
            id: "b", name: "Corner",
            cols: 11, rows: 10, tiles: 94, door: 4,
            mask: [
                "xxxx0000000",
                "xxxx0000000",
                "xxxx0000000",
                "xxxx0000000",
                "00000000000",
                "00000000000",
                "00000000000",
                "00000000000",
                "00000000000",
                "00000000000",
            ]
        },
        {
            id: "f", name: "Steps",
            cols: 10, rows: 10, tiles: 80, door: 2,
            mask: [
                "xxxxxx0000",
                "xxxxxx0000",
                "xx00000000",
                "xx00000000",
                "xx00000000",
                "xx00000000",
                "0000000000",
                "0000000000",
                "0000000000",
                "0000000000",
            ]
        },
        {
            id: "s", name: "Snug",
            cols: 5, rows: 7, tiles: 35, door: 2,
            mask: [
                "00000",
                "00000",
                "00000",
                "00000",
                "00000",
                "00000",
                "00000",
            ]
        },
    ];

    const byId = new Map(MODELS.map(m => [m.id, m]));

    /* An unknown id falls back to the first rather than throwing: a level
       saved against a layout that later went away is still a playable level,
       and the classic room is the right thing to show instead. */
    function get(id) { return byId.get(id) || MODELS[0]; }

    // Is there floor here? Bounds AND mask — a hole is not a tile.
    function has(layout, x, y) {
        if (!layout || x < 0 || y < 0 || y >= layout.rows || x >= layout.cols) return false;
        return layout.mask[y][x] !== "x";
    }

    function tileList(layout) {
        const out = [];
        for (let y = 0; y < layout.rows; y++) {
            for (let x = 0; x < layout.cols; x++) if (has(layout, x, y)) out.push({ x, y });
        }
        return out;
    }

    // The first tile with floor on it, scanning the way a room reads.
    function firstTile(layout) {
        for (let y = 0; y < layout.rows; y++) {
            for (let x = 0; x < layout.cols; x++) if (has(layout, x, y)) return { x, y };
        }
        return { x: 0, y: 0 };
    }

    /* Public rooms add themselves here — see tools/public-room-extract.js.
       They are layouts in every way this file cares about: a size, a mask and
       a door. */
    function register(layout) { if (layout && layout.id) byId.set(layout.id, layout); }

    window.RoomLayouts = { MODELS, DEFAULT: MODELS[0].id, get, has, tileList, firstTile, register };
})();
