/* Furni metadata: how big each one is, and whether you can sit on it.

   WHY THIS EXISTS ALONGSIDE furni-catalogue.js. That one proxies FurniIndex,
   which has the artwork — every state and rotation as a png — and that is what
   the room draws with. What it does NOT have is the two facts the GAME turns
   on: a furni's footprint in tiles, and whether it is a seat. Without the
   first, an armchair blocks one tile instead of two and the player walks
   through half of it. Without the second there is no way to tell a chair from
   a plant, and Fallin' Furni is entirely about that distinction.

   Habbo's own furnidata has both. Origins serves it publicly and complete —
   15,291 floor items, of which 1,668 are sittable — as ~9.6MB of XML at
   /gamedata/furnidata_xml/1. It answers with a 307 first, so the redirect has
   to be followed.

   Distilled hard on the way through: of the twenty-odd fields per item this
   keeps six. The rest (offer ids, rent prices, ad urls, descriptions) is shop
   bookkeeping for a hotel we are not running, and dropping it takes the
   payload from 9.6MB to something a browser can hold without complaint.

   KEYED BY className, because that is the one identifier FurniIndex and Habbo
   agree on — the catalogue proxy already learned that the hard way (see the
   note in furni-catalogue.js about url ids being shared across colour
   variants). Joining the two on className gives artwork and behaviour for the
   same object.

   THE GAME VERY MUCH DOES CALL THIS, and this note used to say the opposite.
   It said a level ships with these fields baked in; it does not. js/room-
   levels.js stores a className, a rotation and a role, and RoomDrop asks
   `meta.sit` at run time for every piece it lands. The only other answer
   available to a player is Furni.libraryMeta, which returns sit:0 for
   everything by construction. Measured across the fifty published levels:
   109 seat classes, every one of them sittable on this endpoint's word
   alone. If this does not answer, Fallin' Furni has no seats.

   WHICH IS WHY THE ANSWER IS STORED. _furnidata.json sits beside this file,
   generated by tools/furni-meta-extract.js and committed like any other
   generated file, and it is what this serves. Origins is still read — by the
   tool on demand, and here on ?refresh=1 — but it is no longer between a
   player and a playable round. See the note in _furnidata.js. */

const { blobStore } = require("./_blobs.js");
const { SECURITY_HEADERS } = require("./_headers");
const { fetchFurnidata } = require("./_furnidata.js");
const { isOwnerWrite } = require("./_auth");

/* The stored copy, required rather than read at run time so the bundler
   carries it into the deployed function. ~1.3MB of JSON, parsed once per
   cold start, against ~9.6MB of XML fetched and parsed from a third party. */
const SNAPSHOT = require("./_furnidata.json");

const CACHE_KEY = "furnidata.json";
const MIN_REFRESH_FRACTION = 0.8;

const json = (statusCode, data) => ({
    statusCode,
    headers: { ...SECURITY_HEADERS, "Cache-Control": "public, max-age=3600" },
    body: JSON.stringify(data)
});

/* The stored copy wins unless something newer has been fetched since.

   This used to be a seven-day cache in front of Origins: serve the blob
   while it was fresh, otherwise fetch 9.6MB of XML and re-parse it, and
   answer 502 if that failed. Which meant the first player after a cache
   expiry waited on a third party to start a round, and a bad day at Origins
   was a day with no seats.

   Now the floor is the snapshot in the repo. It cannot expire, it cannot
   fail, and it is already in memory. `?refresh=1` still reads Origins live
   and writes the result to the blob, and a blob NEWER than the snapshot
   keeps winning afterwards — so a refresh sticks until the next
   tools/furni-meta-extract.js run overtakes it, and neither one silently
   undoes the other.

   What is deliberately gone is the automatic seven-day re-fetch. New furni
   now arrive when somebody runs the tool and commits, which is the trade
   this is making: a stored answer is one that changes on purpose. */
async function getFurniMeta({ force = false } = {}) {
    const store = blobStore("furni");

    if (force) {
        const fresh = await fetchFurnidata();
        /* A refreshed copy is stored only if it looks like the whole thing.
           Whatever is stored here WINS over the committed snapshot from then
           on (see below), so a truncated download, or a day Origins served
           half its furnidata, would otherwise quietly take the seats out of
           Fallin' Furni until somebody noticed and re-ran the tool. Furni are
           added over time, not removed; a count well below the snapshot's is
           a broken fetch, not news. */
        const floor = Math.floor((SNAPSHOT.count || 0) * MIN_REFRESH_FRACTION);
        if (!fresh || !fresh.items || !(fresh.count >= floor)) {
            throw new Error(`refreshed furnidata has ${fresh && fresh.count} items, below ${floor}; not stored`);
        }
        await store.setJSON(CACHE_KEY, fresh).catch(() => { /* served either way */ });
        return fresh;
    }

    const cached = await store.get(CACHE_KEY, { type: "json" }).catch(() => null);
    if (cached && cached.items && cached.fetchedAt > SNAPSHOT.fetchedAt) return cached;
    return SNAPSHOT;
}

/* ANY answer to ?refresh=1 is private to the owner who asked, and is never
   stored by anybody. Every success path below goes out with the public
   hour-long header, and the ?classes= one with an edge-cache header too — so
   an owner's refresh could be kept by the CDN under a URL with refresh=1 in
   it, and the next caller asking the same URL would be handed that stored
   answer without any owner check ever running. The refusal is the same:
   cached, it would stand in for the owner's next attempt. So whatever comes
   back for a refresh, success or refusal, leaves here as no-store. */
function uncached(res) {
    const headers = { ...res.headers, "Cache-Control": "no-store" };
    delete headers["Netlify-CDN-Cache-Control"];
    return { ...res, headers };
}

exports.handler = async (event) => {
    const params = event.queryStringParameters || {};
    if (params.refresh === "1") return uncached(await respond(event, params));
    return respond(event, params);
};

async function respond(event, params) {
    /* A refresh fetches ~9.6MB from Origins and can replace what every
       player's seats are decided by, so it is not something an anonymous
       query string gets to ask for. Owners only, like the furni scans. */
    if (params.refresh === "1" && !(await isOwnerWrite(event))) {
        return { ...json(403, { error: "Only an owner can refresh the furni metadata." }), headers: { ...SECURITY_HEADERS, "Cache-Control": "no-store" } };
    }
    try {
        const data = await getFurniMeta({ force: params.refresh === "1" });

        // A single lookup, for the editor resolving one furni it just picked.
        // An own property only: `?className=constructor` or `__proto__` read
        // straight off the prototype and answered 200 with a function's
        // worth of nothing.
        if (params.className) {
            const hit = Object.prototype.hasOwnProperty.call(data.items, params.className)
                ? data.items[params.className] : null;
            return hit ? json(200, { className: params.className, ...hit })
                : json(404, { error: "No furni by that class name." });
        }

        // Seats only — the list the drop editor mostly wants.
        if (params.sit === "1") {
            const out = {};
            for (const [k, v] of Object.entries(data.items)) if (v.sit) out[k] = v;
            return json(200, { count: Object.keys(out).length, items: out });
        }

        /* A named handful, the same narrowing furni-catalogue.js has.

           Fallin' Furni needs the records for the classes its published
           levels place — about 250 — and was downloading all 15,291 of them
           (1.32MB) on every page load to find them. The editor still asks
           with no parameter and gets everything, because a builder can pick
           any furni there is.

           Exact className match, and a name that matches nothing is simply
           absent: a narrowing, not a lookup. `count` is how many came back,
           so the caller can tell an answer from an empty one.

           THROUGH THE EDGE, which the full response is not. The answer is
           the same for everybody who asks for the same list — no session is
           read — and the list is the same for every player until a level is
           published, so a launch-day crowd becomes a handful of function
           runs. An hour, like the browser header already said; the data
           only changes with a deploy (which clears the edge) or an owner's
           ?refresh=1, and new furni are not in any published level yet. */
        const wanted = (params.classes || "").trim();
        if (wanted) {
            const keep = new Set(wanted.split(",").map(s => s.trim()).filter(Boolean));
            const out = {};
            for (const c of keep) if (Object.prototype.hasOwnProperty.call(data.items, c)) out[c] = data.items[c];
            const res = json(200, { count: Object.keys(out).length, items: out });
            res.headers["Netlify-CDN-Cache-Control"] = "public, durable, s-maxage=3600, stale-while-revalidate=86400";
            return res;
        }

        return json(200, { count: data.count, items: data.items });
    } catch (err) {
        console.error("furni-meta:", err.message);
        /* no-store: the helper's hour-long public header went out on this
           502 too, so one bad moment could be cached in a player's browser
           for an hour — and without furnidata the game has no seats. */
        return { ...json(502, { error: "Could not read furnidata just now." }), headers: { ...SECURITY_HEADERS, "Cache-Control": "no-store" } };
    }
}

module.exports.getFurniMeta = getFurniMeta;
