/* Furni metadata: how big each one is, and whether you can sit on it.

   WHY THIS EXISTS ALONGSIDE furni-catalogue.js. That one proxies FurniIndex,
   which has the artwork — every state and rotation as a png — and that is what
   the room draws with. What it does NOT have is the two facts the GAME turns
   on: a furni's footprint in tiles, and whether it is a seat. Without the
   first, an armchair blocks one tile instead of two and the player walks
   through half of it. Without the second there is no way to tell a chair from
   a plant, and Fallin' Furni is entirely about that distinction.

   Habbo's own furnidata has both. Origins serves it publicly and complete —
   15,291 floor items, of which 1,668 are sittable — as ~9.6MB of XML at
   /gamedata/furnidata_xml/1. It answers with a 307 first, so the redirect has
   to be followed.

   Distilled hard on the way through: of the twenty-odd fields per item this
   keeps six. The rest (offer ids, rent prices, ad urls, descriptions) is shop
   bookkeeping for a hotel we are not running, and dropping it takes the
   payload from 9.6MB to something a browser can hold without complaint.

   KEYED BY className, because that is the one identifier FurniIndex and Habbo
   agree on — the catalogue proxy already learned that the hard way (see the
   note in furni-catalogue.js about url ids being shared across colour
   variants). Joining the two on className gives artwork and behaviour for the
   same object.

   THE GAME VERY MUCH DOES CALL THIS, and this note used to say the opposite.
   It said a level ships with these fields baked in; it does not. js/room-
   levels.js stores a className, a rotation and a role, and RoomDrop asks
   `meta.sit` at run time for every piece it lands. The only other answer
   available to a player is Furni.libraryMeta, which returns sit:0 for
   everything by construction. Measured across the fifty published levels:
   109 seat classes, every one of them sittable on this endpoint's word
   alone. If this does not answer, Fallin' Furni has no seats.

   WHICH IS WHY THE ANSWER IS STORED. _furnidata.json sits beside this file,
   generated by tools/furni-meta-extract.js and committed like any other
   generated file, and it is what this serves. Origins is still read — by the
   tool on demand, and here on ?refresh=1 — but it is no longer between a
   player and a playable round. See the note in _furnidata.js. */

const { blobStore } = require("./_blobs.js");
const { SECURITY_HEADERS } = require("./_headers");
const { fetchFurnidata } = require("./_furnidata.js");

/* The stored copy, required rather than read at run time so the bundler
   carries it into the deployed function. ~1.3MB of JSON, parsed once per
   cold start, against ~9.6MB of XML fetched and parsed from a third party. */
const SNAPSHOT = require("./_furnidata.json");

const CACHE_KEY = "furnidata.json";

const json = (statusCode, data) => ({
    statusCode,
    headers: { ...SECURITY_HEADERS, "Cache-Control": "public, max-age=3600" },
    body: JSON.stringify(data)
});

/* The stored copy wins unless something newer has been fetched since.

   This used to be a seven-day cache in front of Origins: serve the blob
   while it was fresh, otherwise fetch 9.6MB of XML and re-parse it, and
   answer 502 if that failed. Which meant the first player after a cache
   expiry waited on a third party to start a round, and a bad day at Origins
   was a day with no seats.

   Now the floor is the snapshot in the repo. It cannot expire, it cannot
   fail, and it is already in memory. `?refresh=1` still reads Origins live
   and writes the result to the blob, and a blob NEWER than the snapshot
   keeps winning afterwards — so a refresh sticks until the next
   tools/furni-meta-extract.js run overtakes it, and neither one silently
   undoes the other.

   What is deliberately gone is the automatic seven-day re-fetch. New furni
   now arrive when somebody runs the tool and commits, which is the trade
   this is making: a stored answer is one that changes on purpose. */
async function getFurniMeta({ force = false } = {}) {
    const store = blobStore("furni");

    if (force) {
        const fresh = await fetchFurnidata();
        await store.setJSON(CACHE_KEY, fresh).catch(() => { /* served either way */ });
        return fresh;
    }

    const cached = await store.get(CACHE_KEY, { type: "json" }).catch(() => null);
    if (cached && cached.items && cached.fetchedAt > SNAPSHOT.fetchedAt) return cached;
    return SNAPSHOT;
}

exports.handler = async (event) => {
    const params = event.queryStringParameters || {};
    try {
        const data = await getFurniMeta({ force: params.refresh === "1" });

        // A single lookup, for the editor resolving one furni it just picked.
        if (params.className) {
            const hit = data.items[params.className];
            return hit ? json(200, { className: params.className, ...hit })
                : json(404, { error: "No furni by that class name." });
        }

        // Seats only — the list the drop editor mostly wants.
        if (params.sit === "1") {
            const out = {};
            for (const [k, v] of Object.entries(data.items)) if (v.sit) out[k] = v;
            return json(200, { count: Object.keys(out).length, items: out });
        }

        return json(200, { count: data.count, items: data.items });
    } catch (err) {
        return json(502, { error: "Could not read furnidata just now." });
    }
};

module.exports.getFurniMeta = getFurniMeta;
